config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root 'home#index'
  post 'home/convert'
  post 'home/poll'

  get 'home/terms'

  post 'home/remove'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  has_attached_file :file
  # validates_attachment_content_type :file, content_type: [/\Avideo/, /./]
  do_not_validate_attachment_file_type :file

end

app/models/content.rb
class Content < ApplicationRecord
  include AASM
  has_many :attachments, dependent: :destroy

  after_destroy :remove_source_file
  default_scope { order(created_at: :desc) }

  YOUTUBE = 'youtube'
  VIMEO = 'vimeo'

  aasm column: :state do
    state :init, initial: true
    state :downloading
    state :converting
    state :processed


    event :rollback do
      transitions from: :downloading, to: :init
    end

    event :download do
      transitions from: :init, to: :downloading
      transitions from: :downloading, to: :downloading
    end

    event :convert do
      transitions from: :downloading, to: :converting
      transitions from: :converting, to: :converting
    end

    event :finish  do
      transitions from: :converting, to: :processed
      transitions from: :downloading, to: :processed
    end
  end

  def total_file_size
    attachments.map do |attachment|
      return attachment.file.size if attachment.file.present?
      0
    end
  end

  def youtube?
    url.include? YOUTUBE
  end

  def vimeo?
    url.include? VIMEO
  end

  private

  def remove_source_file
    if source_filename && File.exist?(source_filename)
      File.delete source_filename
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :render_to_string
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def convert
    downloader = Downloader.new params[:url]
    downloader.perform do |content|
      ContentDownloader.perform_async content.id
    end

    render json: downloader.response
  end

  def remove
    content = Content.find params[:id]
    content.destroy
  end

  def poll
    @contents = Content.where id: params[:ids]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contents.html.slim
.panel
  .content-container
    - contents.each do |content|
      - if content.init? || content.downloading?
        .row
          .col-md-12.text-center.status-column = content.aasm.human_state
        .row
          .col-md-12
            .progress
              .progress-bar.progress-bar-striped aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" style="width:#{content.progress}%" = "#{content.progress}%"
      - else
        .row
          .col-md-12.text-center.status-column = content.aasm.human_state
        .row
          .col-md-5.human-name
            a href="#{content.url}" = content.human_name
          .col-md-4
            .progress
              .progress-bar.progress-bar-striped aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" style="width:#{content.progress}%" = "#{content.progress}%"
          .col-md-3
            - content.attachments.each do |attachment|
                - if attachment.file.present?
                  a.download href="#{attachment.file.url}" download=""
                    span.fa.fa-download
                    span = "[#{attachment.format}]"
            - if content.processed?
              a href="#" ng-click="remove($event, '#{home_remove_path(id: content.id)}')"
                span.fa.fa-times

app/views/home/index.html.slim
#subscribe.cta-2 ng-controller="ConvertController" ng-init="init('#{home_convert_path}', '#{home_poll_path}')"
  toast
  .container
    .row.text-center
      .col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
        .cta-2-inner
          h1.wow.fadeInDown data-wow-delay="0.1s"  Download your favorite YouTube or Vimeo videos.
          p.wow.fadeInDown data-wow-delay="0.2s"  Paste a Youtube or Vimeo link in the box below.
          .form.wow.fadeInDown data-wow-delay="0.3s"
            = form_tag home_convert_path, method: 'post', class: 'subscribe-form wow zoomIn video-form' do
              .input-group
                input.url-input.form-control autocomplete="off" name="email" placeholder="https://www.youtube.com/watch?v=qs3XoTc_R9o" type="text" ng-model="video_url"
                span.input-group-btn
                  button.btn.btn-primary.submit-button type="submit" ng-click="convert($event)" Convert
    .row.text-center
      .col-md-10.col-md-offset-2
        .poll#poll

    / .row
      / .col-md-8.col-md-offset-2
        / .panel.panel-default
          / .panel-heading Latest
          / = render partial: 'contents', locals: { contents: Content.all  }
.footer-sm.wow.fadeIn
  .container
    .row.text-center
      .col-sm-6.col-sm-offset-3
        .footer-inner
          .footer-img
            h1
              | #{ENV['app_name']}
              sup TM
            p
              |The best, free, YouTube & Vimeo to mp3/mp4 converter online. Use it to download your favorite mp4 videos and mp3 tracks directly from your smartphone or computer. YouTube & Vimeo to mp3 and mp4 conversion is offered for free, doesn't require a registration or the
              |download of any external software: you just have to paste the full url of the Youtube or Vimeo video you're interested in, and click the convert button to start converting to mp4 first then mp3. 
            p &copy; 1999 - 2017
        .footer-social
          / ul
            / li
              / a href="#"
                / i.ion-social-youtube
            / li
              / a href="#"
                / i.ion-social-linkedin
            / li
              / a href="#"
                / i.ion-social-instagram-outline
            / li
              / a href="#"
                / i.ion-social-twitter
/! Scroll To Top
a#back-top.back-to-top.page-scroll href="#main"
  i.ion-ios-arrow-up
/! Scroll To Top Ends
/! Main
/! Wrapper

app/views/home/terms.html.slim
.cta-2.terms
  .container
    .cta-2.terms
      .container
        .row
          .col-md-10.col-md-offset-2
            h1 Terms of Service
            p
              strong Privacy Policy
            p Your privacy is important to us at Vdiio. This Privacy Policy document outlines what data Vdiio receives and how we store, manage, and protect it.
            p This policy is subject to change, and was last updated on May 23rd, 2017.
            p &nbsp;
            p
              strong Logs
            p Vdiio uses log files, which are files that record information including requested webpage resources, IP addresses, browser type, and timestamps. This information is used by Vdiio for troubleshooting, service analysis, and site maintenance. This information cannot be directly linked to personally identifiable information.
            p Log files, and any data therein, are not shared with any third party.
            p
              strong &nbsp;
            p
              strong Collected Information
            p Vdiio receives and stores information that you enter on the website. This includes requested resources, search queries, and DVR settings like the title and artist. This information is stored to monitor and analyze service activity. This information cannot be linked to personally identifiable information.
            p All information you enter is voluntary. None of this information is shared with any third party.
            p &nbsp;
            p
              strong Cookies
            p Vdiio stores your preferences in cookies. While these cookies improve your experience by remembering your settings, they're optional -- all of Vdiio's features and services work without cookies.
            p Cookies may be stored by third parties via third party content embedded in Vdiio, like multimedia players and advertisements. Vdiio has no control over the cookies stored by third parties.
            p &nbsp;
            p
              strong Terms of Service
            p By accessing or using Vdiio, you agree to be bound by Vdiio's Terms of Service as stated in this document. If you do not accept these terms, you are not permitted use of Vdiio nor its services.
            p Vdiio reserves the right to change this document at its sole discretion at any time, for any reason, and you agree to be bound by the then current version of this Terms of Service document.
            p Your acceptance of these Terms of Service terminates automatically if you violate any of its provisions. Vdiio may also terminate this license with you at any time, for any reason, at its sole discretion.
            p No partnership, venture, or employment with Vdiio is created as a result of acceptance of these terms of service.
            p &nbsp;
            p
              strong Content
            p Vdiio is not responsible for the contents of any links or linked materials. Links on Vdiio are not reviewed and do not represent an endorsement by Vdiio. Use of such links is made at your own discretion.
            p You understand that content and materials on Vdiio may not be factual, complete, or current.
            p You agree that all content, information, and data you submit to Vdiio will be collected and governed by Vdiio's Privacy Policy , and that you have the rights to submit that content, information, or data to Vdiio.
            p You may not use any graphics, designs, logos, icons, code, or other content from Vdiio without permission.
            p &nbsp;
            p
              strong Conduct
            p You agree not to:
            ul
              li Violate any laws in your jurisdiction.
              li Impersonate any third party or parties.
              li Disrupt the activities of other Vdiio users.
              li Engage in any activites pertaining to click fraud.
              li Engage in abusive or disruptive behavior to our partners or advertisers.
            p You agree to use Vdiio's services responsibly.
            p &nbsp;
            p
              strong Legality
            p We've received a number of questions about the legality of Vdiio, so we thought it would be helpful to elucidate on the topic here.
            p First and foremost, Vdiio is used by people around the world and legality depends on many factors like one's location and its according laws. It's up to individual users to determine the legality of their activities.
            p For users in the United States, and countries with similar laws, Vdiio is perfectly legal.
            p
              | Vdiio is a Digital Video Recorder (DVR) that lets you make personal recordings of publicly available media for later use and is protected by the Supreme Court's Betamax ruling 
              a href="https://en.wikipedia.org/wiki/Sony_Corp._of_America_v._Universal_City_Studios,_Inc."  (Sony Corporation of America vs Universal City Studios)
              | For context, this is the same ruling that protects the millions of DVRs like
              a href="http://www.tivo.com/"  Tivo
              | in half of American households.
            p Vdiio is simply allowing users to watch publicly available video content later (time-shifting) when Internet connection is not available.
            p
              | Our service is a DVR for publicly available video content, which can be compared to the
              a href="https://en.wikipedia.org/wiki/Sony_Corp._of_America_v._Universal_City_Studios,_Inc."  case with Sony and Universal in 1984
              | If you have no Internet connection, it's totally fine to watch downloaded publicly available video conten like Youtube.
            p &nbsp;
            p
              strong Indemnity
            p You shall indemnify Vdiio and all affiliates, partners, customers, employees, contractors, consultants, and other related entities from any liability, cost, damage, loss, or legal matters arisen from the use or inability of use of Vdiio and/or Vdiio's services.
            p &nbsp;
            p
              strong DMCA
            p
              | Vdiio is intended for, targeted to and used by content creators, educators, students, and other users who want to make
              strong fair use
              | of (creative-commons-licensed or public domain) content found on media sites like Youtube and Vimeo for educational / content creation purposes.
              strong Using Vdiio in a way that infringes copyrights or in any unlawful way is strictly prohibited.
            p &nbsp;
            p Vdiio does not host neither does it provide links to any video or audio content. Vdiio merely accesses content hosted on other media sites on behalf of its users upon demand.
            p &nbsp;
            p
              | We take copyright infringement very seriously and we always want to make sure that our site will only be used fairly and lawfully. If you believe that someone has tried to use Vdiio to access your copyrighted content on Youtube, Vimeo, or any other media provider, please&nbsp;
              a href="mailto:iagesmart18@protonmail.ch" > contact us
              | \:&nbsp; referencing the URL (this would be for example a Youtube URL) of your copyrighted content and we will take immediate action by blocking access to that URL from within Vdiio
            p
              | If you have any other questions regarding DMCA and copyright infringement please&nbsp;
              a href="mailto:iagesmart18@protonmail.ch"  contact us
            p &nbsp;
            p
              strong Questions
            p
              | If you have any questions about this Terms of Service document, don't hesitate to
              a href="mailto:iagesmart18@protonmail.ch"  contact us.
            p &nbsp;

app/views/layouts/application.html.slim
doctype html
html
  head
    title = ENV['app_name']
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    link href="https://fonts.googleapis.com/css?family=Montserrat|Roboto" rel="stylesheet"
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = piwik_tracking_tag
    .wrapper
      nav.navbar.navbar-default.navbar-fixed-top
        .container
          .navbar-header.page-scroll
            button.navbar-toggle aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
            a.navbar-brand.page-scroll href="#main"
              = image_tag 'logo_medium.jpg', alt: 'logo', width: 50
          #bs-example-navbar-collapse-1.collapse.navbar-collapse.navbar-right
            ul.nav.navbar-nav
              li
                a.page-scroll href="#{root_path}" Home
              li
                a.page-scroll href="#{home_terms_path}" Terms of Service
      = yield